name: afro-renaissance
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: KaluEmeKalu/afro_renaissance
    build_command: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate --noinput
      python manage.py sqlflush | python manage.py dbshell
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', '${DJANGO_SUPERUSER_PASSWORD}')"
    run_command: gunicorn afro_renaissance.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 2 --log-level debug --access-logfile - --error-logfile -
    envs:
      - key: PYTHONPATH
        value: "/workspace"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "hammerhead-app-zwj4j.ondigitalocean.app,${APP_DOMAIN}"
      - key: DJANGO_SECRET_KEY
        type: SECRET
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: PORT
        value: "8080"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"