version: '3.8'

services:
  web:
    build: .
    entrypoint: ["bash", "/app/scripts/entrypoint.sh"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - afro_net

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - afro_net

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - afro_net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  afro_net:
    driver: bridge