name: afro-renaissance
region: sfo
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: KaluEmeKalu/afro_renaissance
    build_command: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    run_command: ./scripts/start.sh
    envs:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${APP_DOMAIN}"
      - key: DJANGO_SECRET_KEY
        type: SECRET
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: PORT
        value: "8080"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"