name: afro-renaissance
region: sfo
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: KaluEmeKalu/afro_renaissance
    build_command: |
      apt-get update && apt-get install -y python3-dev libjpeg-dev zlib1g-dev
      pip install -r requirements.txt
      chmod +x scripts/post_deploy.sh
    environment_slug: python
    env:
      - key: PYTHONVERSION
        value: 3.11.7
    run_command: gunicorn afro_renaissance.wsgi:application --bind 0.0.0.0:8080
    deploy_on_push:
      post_deploy:
        - scripts/post_deploy.sh
    envs:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${APP_DOMAIN}"
      - key: DJANGO_SECRET_KEY
        type: SECRET
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"

static_sites:
  - name: static
    github:
      branch: main
      deploy_on_push: true
      repo: KaluEmeKalu/afro_renaissance
    build_command: python manage.py collectstatic --noinput
    output_dir: staticfiles/
    routes:
      - path: /static
      - path: /media